openapi: 3.0.0

info:
  title: "Ecommerce APP API"
  description: "API for Ecommerce app"
  version: "1.0.0"
servers:
  - url: http://localhost:8000/api/v1
paths: 
  /signup:
    post:
      description: "Create new user"
      tags:
        - "Authentication"
      requestBody:
        required: true
        content:
          application/json:
            schema:
              allOf: 
                - $ref: '#/components/schemas/User'
                - type: object
                  properties:
                    passwordConfirmation:
                      type: string
                      example: "Testing12,."
                    name:
                      type: string
                      example: "testing testing"
                    
      responses:
        201:
          description: "Created"
        422:
          description: "Validation Error"
        500:
          description: "Server Error"
  /login:
    post:
      description: "Login to account"
      tags:
        - "Authentication"
      requestBody:
        required: true
        content:
          application/json:
            schema:
              allOf: 
                - $ref: '#/components/schemas/User'
      responses:
        200:
          description: "OK"
        422:
          description: "Validation Error"
        500:
          description: "Server Error"
  /logout:
    post:
      description: "Logout from account"
      tags:
        - "Authentication"
      responses:
        200:
          description: "OK"
        500:
          description: "Server Error"
  /refresh-token:
    post:
      description: "Refresh new token"
      tags:
        - "Authentication"
      security:
        - cookieAuth: []
      responses:
        200:
          description: "OK"
        401:
          description: "Token expired or invalid"
        403:
          description: "Token is missing"
        500:
          description: "Server Error"
        
components:
  schemas:
    User:
      type: object
      properties:
        email:
          type: string
          example: "testing@gmail.com"
        password:
          type: string
          example: "Testing12,."
          description: "password must be at least one uppercase letter, one lowercase letter, one number and one special character"
  securitySchemes:
    cookieAuth:         
      type: apiKey
      in: cookie
      name: jwt 


  