openapi: 3.0.0

info:
  title: "Ecommerce APP API"
  description: "API for ecommerce app"
  version: "1.0.0"
servers:
  - url: http://localhost:8000/api/v1
paths: 
  /carts:
    get:
      description: "Get user cart items"
      tags:
        - "Carts"
      security:
        - bearerAuth: []
      responses:
        200:
          description: "Success"
        401:
          description: "Access Denied"
        500:
          description: "Server Error"
  /carts/{productId}:
    post:
      description: "add product to cart by id"
      tags:
        - "Carts"
      parameters:
      - in: path
        required: true
        name: productId
        schema:
          type: string
      security:
        - bearerAuth: []
      responses:
        200:
          description: "OK"
        401:
          description: "Access Denied"
        500:
          description: "Server Error"
    put:
        description: "decrease product quantity of particular id"
        tags:
          - "Carts"
        parameters:
        - in: path
          required: true
          name: productId
          schema:
            type: string
        security:
          - bearerAuth: []
        responses:
          200:
            description: "OK"
          401:
            description: "Access Denied"
          500:
            description: "Server Error"
    delete:
      description: "remove product from cart"
      tags:
        - "Carts"
      parameters:
      - in: path
        required: true
        name: productId
        schema:
          type: string
      security:
        - bearerAuth: []
      responses:
        200:
          description: "OK"
        401:
          description: "Access Denied"
        500:
          description: "Server Error"
components:
  securitySchemes:
    bearerAuth:
      type: http
      scheme: bearer
      bearerFormat: JWT

  

    

  