openapi: 3.0.0

info:
  title: "Ecommerce APP API"
  description: "API for ecommerce app"
  version: "1.0.0"
servers:
  - url: http://localhost:8000/api/v1
paths: 
  /provinces:
    get:
      description: "Get All Provinces"
      tags:
        - "Checkout"
      responses:
        200:
          description: "Success"
        500:
          description: "Server Error"
  /provinces/{provinceId}:
    get:
      description: "Get City By Province ID"
      tags:
        - "Checkout"
      parameters:
      - in: path
        required: true
        name: provinceId
        schema:
          type: string
        description: Province ID
      responses:
        200:
          description: "Success"
        500:
          description: "Server Error"
  /checkout/cost:
    get:
      description: "Get Shipping Cost"
      tags:
        - "Checkout"
      parameters:
      - in: query
        name: origin
        required: true
        schema:
          type: string
          description: origin city ID
      - in: query
        name: destination
        required: true
        schema:
          type: string
          description: destination city ID
      - in: query
        name: weight
        required: true
        schema:
          type: string
          description: Weight of the product
      responses:
        200:
          description: "Success"
        500:
          description: "Server Error"
  /checkout/pay:
    post:
      description: "Pay Product"
      tags:
        - "Checkout"
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Checkout'
      responses:
        200:
          description: "Success"
        500:
          description: "Server Error"
  /checkout/history:
    get:
      description: "Get Checkout History"
      tags:
        - "Checkout"
      security:
        - bearerAuth: []
      responses:
        200:
          description: "Success"
        500:
          description: "Server Error"
    post:
      description: "Create Checkout History"
      tags:
        - "Checkout"
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/History'
      security:
        - bearerAuth: []
      responses:
        201:
          description: "Success"
        500:
          description: "Server Error"
components:
  schemas:
    Checkout:
      type: object
      properties:
        orderId:
          type: string
          example: "asd781283gaydga67"
        price:
          type: number
          example: 10000
    History:
      type: object
      properties:
        id:
          type: string
          example: "f09c2218-5129-49ad-92d4-e4803406de9d"
        products[]:
          type: array
          items:
            type: object
            properties:
              productId:
                type: string
                example: "35732c79-4d9a-451a-a3eb-5366a9c35687"
              quantity:
                type: number
                example: 4
  securitySchemes:
    bearerAuth:
      type: http
      scheme: bearer
      bearerFormat: JWT

  

    

  